### ISSUE TITLE
Issue with starting

### ISSUE THREAD

**Issue by UnclearCrazy** [Adaaks/Roblox-Clothing-Bot#1]
when i run cmd and type py then the file name

NameError: name 'config' is not defined

**Comment by Adaaks** [comment]
You didn't read the instructions
- You need python 3.10.0, and you MUST enable add to path during installation

Then, you run requirements.bat to install all required modules

**Comment by UnclearCrazy** [comment]
I figured it out, sorry forgot to edit this before.
