### ISSUE TITLE
Uploader why not working?

### ISSUE THREAD

**Issue by dumbovita** [Adaaks/Roblox-Clothing-Bot#5]
![image](https://github.com/Adaaks/Roblox-Clothing-Bot/assets/118517839/f182a48c-44a1-4c44-86b5-62f5c2665065)
I got this error. Why?

**Comment by SilverBrosX** [comment]
Yes, I have the same reason and I don’t know how to solve it, help!

**Comment by dumbovita** [comment]
cuz economy api not working

**Comment by efenatuyo** [comment]
> cuz economy api not working

economy api is working. 
`https://itemconfiguration.roblox.com/v1/avatar-assets/11/upload` is not working
